# generated by datamodel-codegen:
#   filename:  cula.openapi.json
#   timestamp: 2026-04-10T16:39:16+00:00

from __future__ import annotations

import re
from datetime import datetime, timezone
from enum import Enum
from typing import Any
from uuid import UUID

from dateutil import parser as dateutil_parser
from pydantic import AwareDatetime, BaseModel, Field, RootModel, field_validator


class ValidationState(Enum):
    """
    Only sinks with validation state "complete" are returned.
    """

    complete = "complete"


class Technology(Enum):
    """
    The carbon removal technology used.
    """

    biochar = "biochar"


class EventType(Enum):
    """
    The type of event — either a processing step or a delivery between sites.
    """

    step_execution = "step-execution"
    delivery_leg = "delivery-leg"


class StepExecutionType(Enum):
    """
    Present only when eventType is "step-execution".
    """

    material_creation = "material_creation"
    material_processing = "material_processing"
    multi_material_processing = "multi_material_processing"
    material_application = "material_application"


class ConnectionType(Enum):
    """
    "direct" means both events used the same physical container; "pool" means material was drawn from a shared pool.
    """

    pool = "pool"
    direct = "direct"


class AggregatedSinkEventLink(BaseModel):
    """
    A link from one event to a predecessor event, representing material flow.
    """

    eventRef: str = Field(..., description="Event ID of the predecessor event.")
    percentage: float = Field(
        ...,
        description="Fraction (0 to 1) of the predecessor that contributed to this event.",
    )
    connectingContainerIds: list[UUID] = Field(
        ..., description="Container IDs linking the two events."
    )
    connectionType: ConnectionType = Field(
        ...,
        description='"direct" means both events used the same physical container; "pool" means material was drawn from a shared pool.',
    )


class Type(Enum):
    """
    The category of this event in the carbon sink lifecycle. Typical chronological order: biomass_creation → biomass_processing → biomass_delivery → pyrolysis → biochar_delivery_to_processing → biochar_processing → biochar_delivery_to_sink → sink_creation. Not all steps are present in every sink.
    """

    biomass_creation = "biomass_creation"
    biomass_processing = "biomass_processing"
    biomass_delivery = "biomass_delivery"
    pyrolysis = "pyrolysis"
    biochar_delivery_to_processing = "biochar_delivery_to_processing"
    biochar_processing = "biochar_processing"
    biochar_delivery_to_sink = "biochar_delivery_to_sink"
    sink_creation = "sink_creation"


class EventType1(Enum):
    """
    Whether this is a processing step or a delivery between sites.
    """

    step_execution = "step-execution"
    delivery_leg = "delivery-leg"


class WayPoint(RootModel[list[float]]):
    root: list[float] = Field(..., max_length=2, min_length=2)


class Type1(Enum):
    """
    Always "COMPOSITE" for the root calculation node.
    """

    COMPOSITE = "COMPOSITE"


class Type2(Enum):
    """
    The node type determining how its value is derived.
    """

    COMPOSITE = "COMPOSITE"
    STATIC = "STATIC"
    VARIABLE = "VARIABLE"


class Type3(Enum):
    """
    Config type matching the node type.
    """

    COMPOSITE = "COMPOSITE"
    STATIC = "STATIC"
    VARIABLE = "VARIABLE"


class LinkReference(BaseModel):
    """
    Present on STATIC nodes. An external link reference for the emission factor source.
    """

    name: str | None = Field(None, description="Display name of the link.")
    link: str | None = Field(None, description="URL of the external reference.")


class ValueSourceType(Enum):
    """
    "data_point" means the value comes from a machine data point; "event_key" means it comes from an event property; "manual" is used when the value was entered manually (may be omitted from older spec revisions).
    """

    data_point = "data_point"
    event_key = "event_key"
    manual = "manual"


class EventKey(Enum):
    """
    Present when valueSourceType is "event_key".
    """

    combinedMaterialWeightInKg = "combinedMaterialWeightInKg"
    transportationDistanceInKm = "transportationDistanceInKm"


class SourceConfig(BaseModel):
    """
    Present on VARIABLE nodes. Defines where the variable value comes from.
    """

    valueSourceType: ValueSourceType | None = Field(
        None,
        description='"data_point" means the value comes from a machine data point; "event_key" means it comes from an event property; "manual" is used when the value was entered manually (may be omitted from older spec revisions).',
    )
    dpConfigId: UUID | None = Field(
        None, description='Present when valueSourceType is "data_point".'
    )
    eventKey: EventKey | None = Field(
        None, description='Present when valueSourceType is "event_key".'
    )


class Type4(Enum):
    """
    Always "COMPOSITE" for this config type.
    """

    COMPOSITE = "COMPOSITE"


class EmissionCalculationConfig(BaseModel):
    """
    Configuration for a COMPOSITE emission calculation node.
    """

    id: str = Field(..., description="Unique identifier of this config.")
    name: str = Field(..., description="Human-readable name of this calculation step.")
    type: Type4 = Field(..., description='Always "COMPOSITE" for this config type.')
    unit: str | None = Field(None, description="Metric unit for this node's value.")
    explanation: str | None = Field(
        None, description="Human-readable explanation of this calculation step."
    )
    expression: str = Field(
        ...,
        description='A math expression where child node config IDs are used as variable names (e.g. "(configId1) * (configId2)").',
    )
    nodeConfigs: list[dict[str, Any]] | None = Field(
        None,
        description="Configurations for child nodes in this composite calculation.",
    )


class Type5(Enum):
    """
    Discriminator for the proof type.
    """

    file = "file"
    tracking_event = "tracking_event"


class EventType2(Enum):
    """
    Present on tracking_event proofs.
    """

    location_detection = "location_detection"
    ip_address_location = "ip_address_location"


class MetaData(BaseModel):
    """
    Present on tracking_event proofs. Additional metadata.
    """

    distance: float | None = Field(None, description="Distance in meters.")


class ObjectType(Enum):
    """
    The type of provable object this proof is attached to.
    """

    delivery = "delivery"
    material_creation = "material_creation"
    material_processing = "material_processing"
    material_application = "material_application"
    multi_material_processing = "multi_material_processing"
    periodic_emissions_log_request = "periodic_emissions_log_request"


class ProofConfig(BaseModel):
    """
    Configuration describing what aspect of an event this proof covers.
    """

    id: UUID = Field(..., description="Unique identifier of this proof config.")
    objectType: ObjectType = Field(
        ..., description="The type of provable object this proof is attached to."
    )
    key: str = Field(
        ...,
        description="The specific field or aspect of the object that this proof covers.",
    )


class FileReference(BaseModel):
    """
    Reference to an uploaded file in cloud storage. For sensitive file proofs, fileName and cloudStorageId are omitted.
    """

    id: UUID | None = Field(
        None, description="Unique identifier of the file reference."
    )
    fileName: str | None = Field(
        None, description="Name of the file. Omitted for sensitive file proofs."
    )
    type: str | None = Field(
        None,
        description='MIME type of the file (e.g. "image/jpeg", "application/pdf").',
    )
    size: float | None = Field(None, description="File size in bytes.")
    cloudStorageId: str | None = Field(
        None,
        description="ID of the file in cloud storage. Use with the /documents/{id} endpoint to download. Omitted for sensitive file proofs.",
    )
    blurredCloudStorageId: str | None = Field(
        None,
        description="ID of a blurred version of the file in cloud storage. Use with the /documents/{id} endpoint to download.",
    )
    thumbnailCloudStorageId: str | None = Field(
        None,
        description="ID of a thumbnail version of the file in cloud storage. Use with the /documents/{id} endpoint to download.",
    )
    registeredSiteId: UUID | None = Field(
        None, description="ID of the owning registered site."
    )
    fileSourceId: UUID | None = Field(
        None, description="ID of the file source associated with this file reference."
    )


class OrganisationSummary(BaseModel):
    """
    Summary of an organisation involved in the sink.
    """

    id: UUID = Field(..., description="Unique identifier of the organisation.")
    name: str = Field(..., description="Display name of the organisation.")
    description: str | None = Field(
        None, description="Short description of the organisation."
    )
    logoSVG: str | None = Field(
        None, description="SVG markup of the organisation's logo."
    )


class Type6(Enum):
    """
    Category of the material.
    """

    biochar = "biochar"
    biomass = "biomass"
    bio_oil = "bio_oil"
    water = "water"
    other = "other"


class Colors(BaseModel):
    """
    Display colors for visualizing this material.
    """

    darkColor: str | None = Field(None, description="Hex color for dark backgrounds.")
    lightColor: str | None = Field(None, description="Hex color for light backgrounds.")


class Impact(BaseModel):
    """
    Carbon impact information for the material.
    """

    normalized: float | None = Field(
        None, description="Normalized carbon content (e.g. 0.85 = 85% stable carbon)."
    )
    description: str | None = Field(
        None, description="Human-readable description of the impact calculation."
    )


class Type7(Enum):
    """
    The certification standard type.
    """

    ebc_biochar = "ebc_biochar"
    wbc_biochar = "wbc_biochar"


class ApplicationClass(Enum):
    """
    Biochar quality/application class per the certification standard.
    """

    feed_plus = "feed_plus"
    feed = "feed"
    agro = "agro"
    agro_organic = "agro_organic"
    urban = "urban"
    consumer_material = "consumer_material"
    basic_material = "basic_material"
    wbc_premium = "wbc_premium"
    wbc_agro = "wbc_agro"
    wbc_consumer_material = "wbc_consumer_material"


class MetaData1(BaseModel):
    """
    Certification-specific metadata (EBC or WBC biochar).
    """

    type: Type7 | None = Field(None, description="The certification standard type.")
    batchId: str | None = Field(
        None, description="Batch identifier from the certification body."
    )
    batchLink: str | None = Field(
        None,
        description="URL linking to the batch on the certification body's website.",
    )
    applicationClass: ApplicationClass | None = Field(
        None,
        description="Biochar quality/application class per the certification standard.",
    )
    hToCRatio: float | None = Field(
        None, description="Hydrogen-to-carbon molar ratio of the biochar."
    )
    phValue: float | None = Field(None, description="pH value of the biochar.")
    fossilFuelEmissions: float | None = Field(
        None, description="Per ton of dry biochar."
    )
    methaneEmissions: float | None = Field(None, description="Per ton of dry biochar.")


class Material(BaseModel):
    """
    A material tracked in the carbon sink lifecycle (e.g. biochar, biomass).
    """

    id: UUID = Field(..., description="Unique identifier of the material.")
    name: str = Field(..., description="Display name of the material.")
    sitesIds: list[UUID] | None = Field(
        None, description="IDs of sites associated with this material."
    )
    description: str = Field(..., description="Textual description of the material.")
    type: Type6 = Field(..., description="Category of the material.")
    colors: Colors = Field(
        ..., description="Display colors for visualizing this material."
    )
    impact: Impact | None = Field(
        None, description="Carbon impact information for the material."
    )
    certificationId: UUID | None = Field(
        None, description="ID of the material's certification (e.g. EBC certificate)."
    )
    metaData: MetaData1 | None = Field(
        None, description="Certification-specific metadata (EBC or WBC biochar)."
    )


class Type8(Enum):
    """
    Category of the material.
    """

    biochar = "biochar"
    biomass = "biomass"
    bio_oil = "bio_oil"
    water = "water"
    other = "other"


class Material1(BaseModel):
    """
    The material (same shape as Material but without sitesIds and certificationId).
    """

    id: UUID | None = Field(None, description="Unique identifier of the material.")
    name: str | None = Field(None, description="Display name of the material.")
    description: str | None = Field(
        None, description="Textual description of the material."
    )
    type: Type8 | None = Field(None, description="Category of the material.")
    colors: Colors | None = Field(
        None, description="Display colors for visualizing this material."
    )
    impact: Impact | None = Field(
        None, description="Carbon impact information for the material."
    )
    metaData: dict[str, Any] | None = Field(
        None,
        description="Certification-specific metadata (EBC or WBC biochar). Same shape as Material.metaData.",
    )


class MaterialAmount(BaseModel):
    """
    A specific amount of a material inside a container.
    """

    weightInKg: float = Field(
        ..., description="Weight of this material amount in kilograms."
    )
    material: Material1 = Field(
        ...,
        description="The material (same shape as Material but without sitesIds and certificationId).",
    )


class Origin(Enum):
    """
    High-level category of the application medium.
    """

    biological_matrix = "biological_matrix"
    mineral_matrix = "mineral_matrix"
    materials = "materials"
    soil = "soil"
    landfill = "landfill"
    waste_water = "waste_water"
    geological_storage = "geological_storage"


class SinkMatrix(BaseModel):
    """
    The sink matrix defines the application medium for the biochar (e.g. soil, concrete, compost) and its long-term carbon retention properties. Present only on sink_creation events.
    """

    id: UUID = Field(..., description="Unique identifier of the sink matrix.")
    name: str = Field(
        ...,
        description='Display name of the matrix type (e.g. "Agricultural Soil", "Concrete").',
    )
    description: str = Field(
        ..., description="Detailed description of this matrix type."
    )
    normalizedRemainingCarbon: float = Field(
        ...,
        description="Fraction of carbon remaining after the retention period (0 to 1).",
    )
    remainingCarbonPeriodInYears: float = Field(
        ..., description="Time period in years over which carbon retention is measured."
    )
    origin: Origin = Field(
        ..., description="High-level category of the application medium."
    )
    diffuseSinkAuthorized: bool = Field(
        ...,
        description="Whether diffuse (non-localized) sink application is permitted for this matrix.",
    )
    conditions: str = Field(
        ..., description="Textual description of conditions for this matrix type."
    )


class Location(BaseModel):
    """
    Geographic location with coordinates and optional address.
    """

    lat: float = Field(..., description="Latitude.")
    long: float = Field(..., description="Longitude.")
    street: str | None = Field(None, description="Street name and number.")
    city: str | None = Field(None, description="City or municipality name.")
    postcode: str | None = Field(None, description="Postal / ZIP code.")
    country: str | None = Field(None, description="Country name.")
    countryCode: str | None = Field(
        None, description='ISO 3166-1 alpha-2 country code (e.g. "DE", "US").'
    )


class Type9(Enum):
    """
    The LCA database provider.
    """

    eco_invent = "eco_invent"
    epa = "epa"
    ghgenius = "ghgenius"
    environment_canada = "environment_canada"


class SystemModel(Enum):
    """
    The system model used for the LCA calculations.
    """

    cutoff = "cutoff"


class LcaDatabase(BaseModel):
    """
    A Life Cycle Assessment database used as a source for emission factors.
    """

    id: UUID = Field(..., description="Unique identifier of the LCA database.")
    type: Type9 = Field(..., description="The LCA database provider.")
    version: str = Field(..., description='Version of the LCA database (e.g. "3.9.1").')
    systemModel: SystemModel = Field(
        ..., description="The system model used for the LCA calculations."
    )


class LcaMethod(Enum):
    """
    The assessment methodology used.
    """

    ipcc_2021_incl_biogenic_co2 = "ipcc_2021_incl_biogenic_co2"


class LcaActivity(BaseModel):
    """
    A Life Cycle Assessment activity representing an emission factor from an LCA database, bound to a specific product and location.
    """

    id: UUID = Field(..., description="Unique identifier of the LCA activity.")
    lcaDatabaseId: UUID = Field(
        ..., description="ID of the LCA database this activity belongs to."
    )
    lcaMethod: LcaMethod = Field(..., description="The assessment methodology used.")
    title: str = Field(..., description="Title of the LCA activity.")
    description: str = Field(
        ..., description="Detailed description of the LCA activity."
    )
    product: str = Field(..., description="The product this activity applies to.")
    location: str = Field(
        ..., description='Geographic scope of the activity (e.g. "GLO", "DE", "EU").'
    )
    unit: str = Field(
        ...,
        description="Unit for the emission factor (interpreted as kgCO₂e per unit).",
    )
    kgCO2eTotal: float = Field(
        ..., description="Total emission factor in kg CO₂e per unit."
    )
    kgCO2eCo2Fossil: float | None = Field(None, description="Fossil CO₂ component.")
    kgCO2eCh4: float | None = Field(None, description="Methane component.")
    kgCO2eN2oFossil: float | None = Field(None, description="Fossil N₂O component.")
    kgCO2eOghg: float | None = Field(
        None, description="Other greenhouse gas component."
    )
    externalId: str | None = Field(
        None, description="Identifier in the external LCA database."
    )
    externalLink: str | None = Field(
        None, description="URL to the activity in the external LCA database."
    )


class MachineDpConfig(BaseModel):
    """
    Metadata for a single machine data point configuration.
    """

    id: UUID = Field(
        ..., description="Unique identifier of the data point configuration."
    )
    name: str = Field(..., description="Human-readable name of the data point.")
    unit: str | None = Field(None, description='Metric unit (e.g. "°C", "kg", "kWh").')
    siteId: UUID = Field(..., description="ID of the site this data point belongs to.")
    machineId: UUID = Field(
        ..., description="ID of the machine this data point belongs to."
    )
    frequency: str | None = Field(
        None, description="Cron expression defining the sampling frequency."
    )


class MachineDpRequest(BaseModel):
    """
    Request parameters for fetching time-series data for a single data point.
    """

    source: UUID = Field(..., description="The UUID of the machine data point config.")
    start: AwareDatetime = Field(..., description="Start of the time range (ISO 8601).")
    end: AwareDatetime = Field(..., description="End of the time range (ISO 8601).")
    timeBucket: str = Field(
        ...,
        description='Aggregation bucket size. Accepts long-form PostgreSQL intervals (e.g. "5 minutes", "1 hour", "1 day", "1 week") or short-form abbreviations (e.g. "1h", "30m", "1d", "1w", "10s").',
        pattern="^\\d+(\\s+(second|minute|hour|day|week|month|year)s?|\\s*[smhdw])$",
    )


class TimeSeriesEntry(BaseModel):
    """
    A single data point in a time series. The value is the average of all raw readings within the time bucket.
    """

    timestamp: AwareDatetime = Field(
        ..., description="Start of the time bucket (ISO 8601)."
    )
    value: float = Field(
        ..., description="Average of all raw readings within this time bucket."
    )


class Config(BaseModel):
    """
    Configuration for this node, varies by type.
    """

    id: str | None = Field(None, description="Unique identifier of this config.")
    name: str | None = Field(
        None, description="Human-readable name of this calculation step."
    )
    type: Type3 | None = Field(None, description="Config type matching the node type.")
    unit: str | None = Field(
        None, description='Metric unit for this node\'s value (e.g. "kg CO₂e", "km").'
    )
    explanation: str | None = Field(
        None, description="Human-readable explanation of this emission factor."
    )
    expression: str | None = Field(
        None,
        description='Present on COMPOSITE nodes. A math expression where child node config IDs are used as variable names (e.g. "(configId1) * (configId2)").',
    )
    nodeConfigs: list[dict[str, Any]] | None = Field(
        None, description="Present on COMPOSITE nodes. Configs for child nodes."
    )
    value: float | None = Field(
        None, description="Present on STATIC nodes. The fixed emission factor value."
    )
    lcaActivityId: UUID | None = Field(
        None,
        description="Present on STATIC nodes. References an LCA activity providing the emission factor.",
    )
    fileReference: FileReference | None = Field(
        None,
        description="Present on STATIC nodes. A file providing evidence for the emission factor.",
    )
    linkReference: LinkReference | None = Field(
        None,
        description="Present on STATIC nodes. An external link reference for the emission factor source.",
    )
    sourceConfig: SourceConfig | None = Field(
        None,
        description="Present on VARIABLE nodes. Defines where the variable value comes from.",
    )


class EmissionCalculationNode(BaseModel):
    """
    A node in the emission calculation tree. Can be COMPOSITE (with nested nodes), STATIC (fixed value, optionally referencing an LCA activity), or VARIABLE (derived from a data point or event property).
    """

    id: str = Field(..., description="Unique identifier of this calculation node.")
    type: Type2 = Field(
        ..., description="The node type determining how its value is derived."
    )
    value: float = Field(..., description="Calculated emission value for this node.")
    config: Config = Field(
        ..., description="Configuration for this node, varies by type."
    )
    nodes: list[EmissionCalculationNode] | None = Field(
        None, description="Present on COMPOSITE nodes. Child calculation nodes."
    )


class EventProof(BaseModel):
    """
    Evidence attached to an event. Discriminated by "type": "file" proofs link to uploaded documents (photos, PDFs); "tracking_event" proofs are automated location/IP detections.
    """

    id: str = Field(..., description="Unique identifier of this proof.")
    timestamp: AwareDatetime = Field(
        ..., description="When this proof was recorded (ISO 8601)."
    )
    type: Type5 = Field(..., description="Discriminator for the proof type.")

    @field_validator("timestamp", mode="before")
    @classmethod
    def coerce_proof_timestamp(cls, v: Any) -> Any:
        """Accept locale-style datetimes the API sometimes returns (e.g. with TZ names in parentheses)."""
        if not isinstance(v, str):
            return v
        s = re.sub(r"\s*\([^)]*\)\s*$", "", v.strip())
        try:
            dt = dateutil_parser.parse(s)
        except (ValueError, TypeError, OverflowError):
            return v
        if dt.tzinfo is None:
            dt = dt.replace(tzinfo=timezone.utc)
        return dt
    proofConfigs: list[ProofConfig] = Field(
        ...,
        description="Configurations describing what aspects of the event this proof covers.",
    )
    isSensitive: bool | None = Field(
        None,
        description="Present on file proofs. If true, fileReference is redacted (no fileName or cloudStorageId).",
    )
    fileReference: FileReference | None = Field(
        None,
        description="Present on file proofs. The referenced file (photo, PDF, etc.).",
    )
    thumbnailFileReference: FileReference | None = Field(
        None, description="Present on file proofs. A thumbnail version of the file."
    )
    eventType: EventType2 | None = Field(
        None, description="Present on tracking_event proofs."
    )
    metaData: MetaData | None = Field(
        None, description="Present on tracking_event proofs. Additional metadata."
    )


class Site(BaseModel):
    """
    A site involved in the sink's supply chain.
    """

    siteRef: UUID = Field(..., description="The site's ID.")
    name: str = Field(..., description="Display name of the site.")
    location: Location
    organisationRef: UUID | None = Field(
        None, description="The owning organisation's ID (if the site is registered)."
    )


class MaterialContainer(BaseModel):
    """
    A material container with its content fully resolved with material details.
    """

    id: UUID = Field(..., description="Unique identifier of the container.")
    created: str = Field(
        ...,
        description="Milliseconds since Unix epoch (1970-01-01T00:00:00Z) as a string.",
    )
    content: list[MaterialAmount] = Field(
        ..., description="The material amounts inside this container."
    )


class MachineDataInRange(BaseModel):
    """
    Time-series data for a single machine data point within the requested range.
    """

    id: UUID | None = Field(None, description="The data point config ID.")
    config: MachineDpConfig | None = Field(
        None, description="The data point configuration metadata."
    )
    data: list[TimeSeriesEntry] | None = Field(
        None, description="The time-series values."
    )


class EmissionCalculation(BaseModel):
    """
    A tree-structured emission calculation. The root is always a COMPOSITE node that aggregates child nodes (which can be STATIC values, VARIABLE values, or nested COMPOSITE nodes). The "value" field holds the computed result in kg CO₂e.
    """

    id: str = Field(..., description="Unique identifier of this calculation node.")
    type: Type1 = Field(
        ..., description='Always "COMPOSITE" for the root calculation node.'
    )
    value: float = Field(..., description="Calculated emission value in kg CO₂e.")
    config: EmissionCalculationConfig = Field(
        ..., description="Configuration describing how this node's value is computed."
    )
    nodes: list[EmissionCalculationNode] = Field(
        ..., description="Child calculation nodes."
    )


class Event(BaseModel):
    """
    A registry event in the sink lifecycle. Discriminated by "type" and "eventType". Delivery events have sender/receiver sites and payload. Step execution events have a location and input/output containers.
    """

    type: Type = Field(
        ...,
        description="The category of this event in the carbon sink lifecycle. Typical chronological order: biomass_creation → biomass_processing → biomass_delivery → pyrolysis → biochar_delivery_to_processing → biochar_processing → biochar_delivery_to_sink → sink_creation. Not all steps are present in every sink.",
    )
    eventRef: str = Field(..., description="ID of the corresponding event.")
    eventType: EventType1 = Field(
        ...,
        description="Whether this is a processing step or a delivery between sites.",
    )
    lcaActivities: list[LcaActivity] | None = Field(
        None,
        description="LCA activities referenced by this event's emission calculations.",
    )
    emissions: EmissionCalculation = Field(
        ..., description="Tree-structured emission calculation for this event."
    )
    proofs: list[EventProof] = Field(
        ...,
        description="Evidence (photos, documents, tracking events) attached to this event.",
    )
    created: str = Field(
        ...,
        description="Milliseconds since Unix epoch (1970-01-01T00:00:00Z) as a string.",
    )
    wayPoints: list[WayPoint] = Field(
        ...,
        description="Array of [longitude, latitude] coordinate pairs (route for deliveries).",
    )
    senderSiteId: UUID | None = Field(
        None, description="Present on delivery events. Site that sent the material."
    )
    receiverSiteId: UUID | None = Field(
        None, description="Present on delivery events. Site that received the material."
    )
    payload: list[MaterialContainer] | None = Field(
        None,
        description="Present on delivery events. The containers being transported.",
    )
    transportationDistanceInKm: float | None = Field(
        None, description="Present on delivery events. Distance in kilometers."
    )
    location: Location | None = Field(
        None,
        description="Present on step execution events. The location where the step was performed (falls back to the site's location).",
    )
    siteId: UUID | None = Field(
        None,
        description="Present on step execution events. The site where the step was executed.",
    )
    input: list[MaterialContainer] | None = Field(
        None,
        description="Present on pyrolysis, biomass_processing, biochar_processing, and sink_creation events. The input material containers.",
    )
    output: list[MaterialContainer] | None = Field(
        None,
        description="Present on biomass_creation, biomass_processing, biochar_processing, and pyrolysis events. The output material containers.",
    )
    matrixType: SinkMatrix | None = None


class EventInfo(BaseModel):
    """
    A graph node combining graph metadata with the full registry event payload.
    """

    contributionFactor: float | None = Field(
        None,
        description="Share of total impact attributed to this event for the sink (0 to 1).",
    )
    isCompleted: bool | None = Field(
        None, description="Whether all required data for this event has been recorded."
    )
    eventType: EventType | None = Field(
        None,
        description="The type of event — either a processing step or a delivery between sites.",
    )
    stepExecutionType: StepExecutionType | None = Field(
        None, description='Present only when eventType is "step-execution".'
    )
    links: list[AggregatedSinkEventLink] | None = Field(
        None, description="Back-links to predecessor events in the graph."
    )
    event: Event | None = Field(
        None,
        description="The full event payload for this graph node.",
    )


class EventGraph(BaseModel):
    """
    Directed graph of events that make up the sink's lifecycle. The graph traces the full supply chain from biomass creation, through deliveries, pyrolysis, processing, and final application as a carbon sink.
    The root node is the final event (sink creation / material application). Each node's "links" array points backward to its predecessor events. To reconstruct the chronological supply chain, traverse from leaf nodes (biomass creation) toward the root (sink creation). A typical chain looks like: biomass_creation → biomass_delivery → pyrolysis → biochar_delivery_to_sink → sink_creation. Processing and additional delivery steps may appear between stages.
    """

    root: str | None = Field(
        None,
        description="Event ID of the root node (the sink creation event — the final step in the lifecycle).",
    )
    nodes: dict[str, EventInfo] | None = Field(
        None, description="Map of event ID to event info node."
    )


class Sink(BaseModel):
    """
    A carbon sink with its full registry context, including the event graph tracing its full lifecycle from biomass creation through pyrolysis to final application.
    """

    id: UUID | None = Field(None, description="Unique identifier of the sink.")
    created: str | None = Field(
        None,
        description="Milliseconds since Unix epoch (1970-01-01T00:00:00Z) as a string.",
    )
    location: Location | None = Field(
        None, description="Geographic location of the sink."
    )
    normalisedGrossImpact: float | None = Field(
        None,
        description="Gross carbon impact in kg CO₂e sequestered, before subtracting process emissions.",
    )
    normalisedNetImpact: float | None = Field(
        None,
        description="Net carbon impact in kg CO₂e sequestered, after subtracting process emissions from the event graph.",
    )
    validationState: ValidationState | None = Field(
        None, description='Only sinks with validation state "complete" are returned.'
    )
    technology: Technology | None = Field(
        None, description="The carbon removal technology used."
    )
    isPublic: bool | None = Field(
        None, description="Whether this sink is publicly visible on the registry."
    )
    sinkSubmissionsIds: list[UUID] | None = Field(
        None, description="IDs of submissions of this sink to external registries."
    )
    ownerOrganisationId: UUID | None = Field(
        None, description="ID of the organisation that owns the sink."
    )
    carbonCaptureSiteId: UUID | None = Field(
        None, description="The site that captures the carbon (e.g. pyrolysis site)."
    )
    materialId: UUID | None = Field(
        None,
        description="ID of the sunken biochar material. This material is also included in the materials array, which contains all materials involved in the sink's supply chain.",
    )
    confirmationDocumentFileReferenceId: UUID | None = Field(
        None,
        description="File reference ID for the confirmation document. Find the matching FileReference in event proofs and use its cloudStorageId with the /documents/{id} endpoint to download.",
    )
    eventGraph: EventGraph | None = Field(
        None, description="Directed graph of all events in this sink's lifecycle."
    )
    sites: list[Site] | None = Field(
        None, description="All sites involved in the sink's supply chain."
    )
    organisations: list[OrganisationSummary] | None = Field(
        None, description="All organisations involved in the sink's supply chain."
    )
    materials: list[Material] | None = Field(
        None, description="All materials referenced by the sink."
    )
    utilizedContainers: list[MaterialContainer] | None = Field(
        None, description="All material containers utilized in this sink."
    )
    lcaDatabases: list[LcaDatabase] | None = Field(
        None, description="LCA databases referenced by emission calculations."
    )
    lcaActivities: list[LcaActivity] | None = Field(
        None,
        description="LCA activities (emission factors) used in emission calculations.",
    )


EmissionCalculationNode.model_rebuild()
